#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinitely with
#A sleep 2 in between each iteration.
#Displays "I am invincible!!!" in between each iteration

handle_sigterm() {
		echo "I am invincible!!!"
		exit 0
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
