#!/usr/bin/env bash
# This script tells the story of /etc/passwd

# Read the file /etc/passwd line by line
while IFS=: read -r username _ userid groupid _ homedir shell; do
    # Extracting user info from /etc/passwd
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
